#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update and upgrade the system
apt-get -y update && apt-get -y upgrade

# Install Nginx
apt-get -y install nginx

# Create directories and files for the web root
touch /etc/nginx/index.html
echo "Hello World!" > /etc/nginx/index.html
touch /etc/nginx/404.html
echo "Ceci n'est pas une page" > /etc/nginx/404.html

# Configure Nginx
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
